/**
 * Philippines Administrative Hierarchy Registry
 * Structured as Island Groups -> Administrative Regions -> Provinces & Districts.
 * Provides canonical coordinate centers, bounding boxes, and GeoJSON chunk keys.
 */

export interface RegionTreeNode {
  id: string;
  name: string;
  shortName?: string;
  type: 'nationwide' | 'island_group' | 'region' | 'province';
  chunkKey: string;
  parentPath?: string;
  center: [number, number];
  zoom: number;
  bounds?: [[number, number], [number, number]]; // [[minLat, minLng], [maxLat, maxLng]]
  children?: RegionTreeNode[];
}

export const PHILIPPINES_REGION_TREE: RegionTreeNode[] = [
  {
    id: 'philippines',
    name: 'Nationwide (Philippines)',
    shortName: 'Philippines',
    type: 'nationwide',
    chunkKey: 'philippines',
    center: [12.8797, 121.7740],
    zoom: 6,
    bounds: [
      [4.5, 116.5],
      [21.5, 127.5],
    ],
  },
  {
    id: 'luzon',
    name: 'Luzon Island Group',
    shortName: 'Luzon',
    type: 'island_group',
    chunkKey: 'philippines',
    center: [15.5, 121.0],
    zoom: 7,
    children: [
      {
        id: 'ncr',
        name: 'NCR (Metro Manila)',
        shortName: 'Metro Manila',
        type: 'region',
        chunkKey: 'ncr',
        parentPath: 'Luzon',
        center: [14.5995, 121.0364],
        zoom: 11,
        bounds: [
          [14.35, 120.90],
          [14.80, 121.15],
        ],
        children: [
          {
            id: 'manila',
            name: 'City of Manila',
            shortName: 'Manila',
            type: 'province',
            chunkKey: 'ncr',
            parentPath: 'Luzon > NCR',
            center: [14.5995, 120.9842],
            zoom: 12,
            bounds: [
              [14.55, 120.95],
              [14.63, 121.02],
            ],
          },
          {
            id: 'quezon_city',
            name: 'Quezon City',
            shortName: 'QC',
            type: 'province',
            chunkKey: 'ncr',
            parentPath: 'Luzon > NCR',
            center: [14.6760, 121.0437],
            zoom: 12,
            bounds: [
              [14.60, 120.98],
              [14.75, 121.12],
            ],
          },
          {
            id: 'makati',
            name: 'Makati City',
            shortName: 'Makati',
            type: 'province',
            chunkKey: 'ncr',
            parentPath: 'Luzon > NCR',
            center: [14.5547, 121.0244],
            zoom: 13,
            bounds: [
              [14.52, 121.00],
              [14.58, 121.06],
            ],
          },
          {
            id: 'pasig',
            name: 'Pasig City',
            shortName: 'Pasig',
            type: 'province',
            chunkKey: 'ncr',
            parentPath: 'Luzon > NCR',
            center: [14.5764, 121.0851],
            zoom: 13,
            bounds: [
              [14.54, 121.05],
              [14.61, 121.12],
            ],
          },
          {
            id: 'taguig',
            name: 'Taguig City',
            shortName: 'Taguig',
            type: 'province',
            chunkKey: 'ncr',
            parentPath: 'Luzon > NCR',
            center: [14.5176, 121.0509],
            zoom: 13,
            bounds: [
              [14.48, 121.02],
              [14.55, 121.08],
            ],
          },
          {
            id: 'caloocan',
            name: 'Caloocan City',
            shortName: 'Caloocan',
            type: 'province',
            chunkKey: 'ncr',
            parentPath: 'Luzon > NCR',
            center: [14.6416, 120.9762],
            zoom: 12,
            bounds: [
              [14.62, 120.95],
              [14.78, 121.06],
            ],
          },
          {
            id: 'paranaque',
            name: 'Parañaque City',
            shortName: 'Parañaque',
            type: 'province',
            chunkKey: 'ncr',
            parentPath: 'Luzon > NCR',
            center: [14.4793, 121.0198],
            zoom: 13,
            bounds: [
              [14.44, 120.97],
              [14.52, 121.05],
            ],
          },
        ],
      },
      {
        id: 'car',
        name: 'CAR (Cordillera)',
        shortName: 'Cordillera',
        type: 'region',
        chunkKey: 'car',
        parentPath: 'Luzon',
        center: [17.0754, 121.0028],
        zoom: 8,
        bounds: [
          [16.15, 120.40],
          [18.60, 121.75],
        ],
        children: [
          {
            id: 'benguet',
            name: 'Benguet (Baguio)',
            shortName: 'Benguet',
            type: 'province',
            chunkKey: 'car',
            parentPath: 'Luzon > CAR',
            center: [16.4023, 120.5960],
            zoom: 10,
            bounds: [
              [16.20, 120.45],
              [16.85, 120.90],
            ],
          },
          {
            id: 'abra',
            name: 'Abra Province',
            shortName: 'Abra',
            type: 'province',
            chunkKey: 'car',
            parentPath: 'Luzon > CAR',
            center: [17.5959, 120.7674],
            zoom: 10,
            bounds: [
              [17.15, 120.45],
              [18.00, 121.15],
            ],
          },
          {
            id: 'apayao',
            name: 'Apayao Province',
            shortName: 'Apayao',
            type: 'province',
            chunkKey: 'car',
            parentPath: 'Luzon > CAR',
            center: [18.1500, 121.2000],
            zoom: 10,
            bounds: [
              [17.70, 120.95],
              [18.55, 121.50],
            ],
          },
          {
            id: 'ifugao',
            name: 'Ifugao Province',
            shortName: 'Ifugao',
            type: 'province',
            chunkKey: 'car',
            parentPath: 'Luzon > CAR',
            center: [16.8500, 121.1500],
            zoom: 10,
            bounds: [
              [16.55, 120.85],
              [17.10, 121.45],
            ],
          },
          {
            id: 'kalinga',
            name: 'Kalinga Province',
            shortName: 'Kalinga',
            type: 'province',
            chunkKey: 'car',
            parentPath: 'Luzon > CAR',
            center: [17.4500, 121.2500],
            zoom: 10,
            bounds: [
              [17.15, 120.90],
              [17.65, 121.65],
            ],
          },
          {
            id: 'mountain_province',
            name: 'Mountain Province',
            shortName: 'Mt Province',
            type: 'province',
            chunkKey: 'car',
            parentPath: 'Luzon > CAR',
            center: [17.0800, 121.0500],
            zoom: 10,
            bounds: [
              [16.90, 120.75],
              [17.25, 121.50],
            ],
          },
        ],
      },
      {
        id: 'r1',
        name: 'Region I (Ilocos Region)',
        shortName: 'Ilocos',
        type: 'region',
        chunkKey: 'ilocos_cagayan',
        parentPath: 'Luzon',
        center: [16.8906, 120.5739],
        zoom: 8,
        bounds: [
          [15.70, 119.70],
          [18.65, 120.90],
        ],
        children: [
          {
            id: 'ilocos_norte',
            name: 'Ilocos Norte',
            shortName: 'Ilocos Norte',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region I',
            center: [18.1960, 120.5927],
            zoom: 10,
            bounds: [
              [17.75, 120.40],
              [18.65, 120.90],
            ],
          },
          {
            id: 'ilocos_sur',
            name: 'Ilocos Sur',
            shortName: 'Ilocos Sur',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region I',
            center: [17.5747, 120.3869],
            zoom: 10,
            bounds: [
              [16.85, 120.30],
              [17.90, 120.85],
            ],
          },
          {
            id: 'la_union',
            name: 'La Union',
            shortName: 'La Union',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region I',
            center: [16.6159, 120.3209],
            zoom: 10,
            bounds: [
              [16.20, 120.25],
              [16.90, 120.55],
            ],
          },
          {
            id: 'pangasinan',
            name: 'Pangasinan',
            shortName: 'Pangasinan',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region I',
            center: [15.9758, 120.3340],
            zoom: 9,
            bounds: [
              [15.65, 119.75],
              [16.30, 120.90],
            ],
          },
        ],
      },
      {
        id: 'r2',
        name: 'Region II (Cagayan Valley)',
        shortName: 'Cagayan Valley',
        type: 'region',
        chunkKey: 'ilocos_cagayan',
        parentPath: 'Luzon',
        center: [17.6132, 121.7270],
        zoom: 8,
        bounds: [
          [15.70, 120.70],
          [20.90, 122.60],
        ],
        children: [
          {
            id: 'batanes',
            name: 'Batanes Province',
            shortName: 'Batanes',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region II',
            center: [20.4485, 121.9708],
            zoom: 9,
            bounds: [
              [20.25, 121.75],
              [21.15, 122.15],
            ],
          },
          {
            id: 'cagayan',
            name: 'Cagayan Province',
            shortName: 'Cagayan',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region II',
            center: [18.2500, 121.7500],
            zoom: 9,
            bounds: [
              [17.50, 121.20],
              [19.00, 122.40],
            ],
          },
          {
            id: 'isabela',
            name: 'Isabela Province',
            shortName: 'Isabela',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region II',
            center: [16.9754, 121.8107],
            zoom: 9,
            bounds: [
              [16.35, 121.30],
              [17.65, 122.60],
            ],
          },
          {
            id: 'nueva_vizcaya',
            name: 'Nueva Vizcaya',
            shortName: 'N. Vizcaya',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region II',
            center: [16.3500, 121.2000],
            zoom: 10,
            bounds: [
              [15.90, 120.75],
              [16.70, 121.50],
            ],
          },
          {
            id: 'quirino',
            name: 'Quirino Province',
            shortName: 'Quirino',
            type: 'province',
            chunkKey: 'ilocos_cagayan',
            parentPath: 'Luzon > Region II',
            center: [16.2800, 121.5500],
            zoom: 10,
            bounds: [
              [15.85, 121.30],
              [16.60, 121.85],
            ],
          },
        ],
      },
      {
        id: 'central_luzon',
        name: 'Region III (Central Luzon)',
        shortName: 'Central Luzon',
        type: 'region',
        chunkKey: 'central_luzon',
        parentPath: 'Luzon',
        center: [15.4828, 120.7120],
        zoom: 8,
        bounds: [
          [14.30, 119.70],
          [16.60, 122.35],
        ],
        children: [
          {
            id: 'bataan',
            name: 'Bataan Province',
            shortName: 'Bataan',
            type: 'province',
            chunkKey: 'central_luzon',
            parentPath: 'Luzon > Region III',
            center: [14.6500, 120.4500],
            zoom: 10,
            bounds: [
              [14.35, 120.25],
              [14.95, 120.65],
            ],
          },
          {
            id: 'bulacan',
            name: 'Bulacan Province',
            shortName: 'Bulacan',
            type: 'province',
            chunkKey: 'central_luzon',
            parentPath: 'Luzon > Region III',
            center: [14.9500, 120.9500],
            zoom: 10,
            bounds: [
              [14.65, 120.65],
              [15.30, 121.35],
            ],
          },
          {
            id: 'nueva_ecija',
            name: 'Nueva Ecija',
            shortName: 'N. Ecija',
            type: 'province',
            chunkKey: 'central_luzon',
            parentPath: 'Luzon > Region III',
            center: [15.5500, 121.0500],
            zoom: 9,
            bounds: [
              [15.10, 120.65],
              [16.15, 121.45],
            ],
          },
          {
            id: 'pampanga',
            name: 'Pampanga Province',
            shortName: 'Pampanga',
            type: 'province',
            chunkKey: 'central_luzon',
            parentPath: 'Luzon > Region III',
            center: [15.0500, 120.6500],
            zoom: 10,
            bounds: [
              [14.80, 120.40],
              [15.25, 120.85],
            ],
          },
          {
            id: 'tarlac',
            name: 'Tarlac Province',
            shortName: 'Tarlac',
            type: 'province',
            chunkKey: 'central_luzon',
            parentPath: 'Luzon > Region III',
            center: [15.5000, 120.5500],
            zoom: 10,
            bounds: [
              [15.20, 120.30],
              [15.85, 120.80],
            ],
          },
          {
            id: 'zambales',
            name: 'Zambales Province',
            shortName: 'Zambales',
            type: 'province',
            chunkKey: 'central_luzon',
            parentPath: 'Luzon > Region III',
            center: [15.3000, 120.1000],
            zoom: 9,
            bounds: [
              [14.75, 119.75],
              [15.85, 120.35],
            ],
          },
          {
            id: 'aurora',
            name: 'Aurora Province',
            shortName: 'Aurora',
            type: 'province',
            chunkKey: 'central_luzon',
            parentPath: 'Luzon > Region III',
            center: [15.7500, 121.6000],
            zoom: 9,
            bounds: [
              [14.95, 121.30],
              [16.50, 122.35],
            ],
          },
        ],
      },
      {
        id: 'r4a',
        name: 'Region IV-A (CALABARZON)',
        shortName: 'CALABARZON',
        type: 'region',
        chunkKey: 'calabarzon_mimaropa',
        parentPath: 'Luzon',
        center: [14.1008, 121.0794],
        zoom: 8,
        bounds: [
          [13.50, 120.40],
          [15.15, 122.65],
        ],
        children: [
          {
            id: 'batangas',
            name: 'Batangas Province',
            shortName: 'Batangas',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > CALABARZON',
            center: [13.8500, 121.0500],
            zoom: 10,
            bounds: [
              [13.50, 120.55],
              [14.20, 121.40],
            ],
          },
          {
            id: 'cavite',
            name: 'Cavite Province',
            shortName: 'Cavite',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > CALABARZON',
            center: [14.2800, 120.9000],
            zoom: 10,
            bounds: [
              [14.10, 120.60],
              [14.50, 121.10],
            ],
          },
          {
            id: 'laguna',
            name: 'Laguna Province',
            shortName: 'Laguna',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > CALABARZON',
            center: [14.2500, 121.3500],
            zoom: 10,
            bounds: [
              [14.05, 120.95],
              [14.55, 121.60],
            ],
          },
          {
            id: 'quezon',
            name: 'Quezon Province',
            shortName: 'Quezon',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > CALABARZON',
            center: [14.1500, 121.9000],
            zoom: 9,
            bounds: [
              [13.20, 121.35],
              [15.15, 122.65],
            ],
          },
          {
            id: 'rizal',
            name: 'Rizal Province',
            shortName: 'Rizal',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > CALABARZON',
            center: [14.6000, 121.2500],
            zoom: 10,
            bounds: [
              [14.40, 121.10],
              [14.90, 121.50],
            ],
          },
        ],
      },
      {
        id: 'r4b',
        name: 'MIMAROPA (Region IV-B)',
        shortName: 'MIMAROPA',
        type: 'region',
        chunkKey: 'calabarzon_mimaropa',
        parentPath: 'Luzon',
        center: [12.0000, 120.0000],
        zoom: 7,
        bounds: [
          [7.50, 116.85],
          [14.20, 122.80],
        ],
        children: [
          {
            id: 'palawan',
            name: 'Palawan Province',
            shortName: 'Palawan',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > MIMAROPA',
            center: [9.7392, 118.7353],
            zoom: 8,
            bounds: [
              [7.50, 116.85],
              [12.45, 120.40],
            ],
          },
          {
            id: 'oriental_mindoro',
            name: 'Oriental Mindoro',
            shortName: 'Or. Mindoro',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > MIMAROPA',
            center: [13.0000, 121.3500],
            zoom: 9,
            bounds: [
              [12.15, 121.00],
              [13.55, 121.65],
            ],
          },
          {
            id: 'occidental_mindoro',
            name: 'Occidental Mindoro',
            shortName: 'Occ. Mindoro',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > MIMAROPA',
            center: [13.0000, 120.7500],
            zoom: 9,
            bounds: [
              [12.15, 120.30],
              [13.60, 121.15],
            ],
          },
          {
            id: 'marinduque',
            name: 'Marinduque',
            shortName: 'Marinduque',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > MIMAROPA',
            center: [13.4000, 121.9000],
            zoom: 10,
            bounds: [
              [13.15, 121.75],
              [13.65, 122.20],
            ],
          },
          {
            id: 'romblon',
            name: 'Romblon Province',
            shortName: 'Romblon',
            type: 'province',
            chunkKey: 'calabarzon_mimaropa',
            parentPath: 'Luzon > MIMAROPA',
            center: [12.5000, 122.3000],
            zoom: 9,
            bounds: [
              [11.95, 121.75],
              [13.00, 122.75],
            ],
          },
        ],
      },
      {
        id: 'bicol',
        name: 'Region V (Bicol Region)',
        shortName: 'Bicol',
        type: 'region',
        chunkKey: 'bicol',
        parentPath: 'Luzon',
        center: [13.4210, 123.4136],
        zoom: 8,
        bounds: [
          [11.65, 122.25],
          [14.55, 124.50],
        ],
        children: [
          {
            id: 'albay',
            name: 'Albay (Legazpi)',
            shortName: 'Albay',
            type: 'province',
            chunkKey: 'bicol',
            parentPath: 'Luzon > Region V',
            center: [13.1775, 123.6300],
            zoom: 10,
            bounds: [
              [12.95, 123.25],
              [13.45, 124.00],
            ],
          },
          {
            id: 'camarines_sur',
            name: 'Camarines Sur',
            shortName: 'Cam Sur',
            type: 'province',
            chunkKey: 'bicol',
            parentPath: 'Luzon > Region V',
            center: [13.5500, 123.3500],
            zoom: 9,
            bounds: [
              [13.15, 122.65],
              [14.10, 123.95],
            ],
          },
          {
            id: 'camarines_norte',
            name: 'Camarines Norte',
            shortName: 'Cam Norte',
            type: 'province',
            chunkKey: 'bicol',
            parentPath: 'Luzon > Region V',
            center: [14.1500, 122.7500],
            zoom: 10,
            bounds: [
              [13.85, 122.35],
              [14.45, 123.10],
            ],
          },
          {
            id: 'sorsogon',
            name: 'Sorsogon Province',
            shortName: 'Sorsogon',
            type: 'province',
            chunkKey: 'bicol',
            parentPath: 'Luzon > Region V',
            center: [12.8500, 123.9500],
            zoom: 10,
            bounds: [
              [12.55, 123.65],
              [13.15, 124.25],
            ],
          },
          {
            id: 'catanduanes',
            name: 'Catanduanes',
            shortName: 'Catanduanes',
            type: 'province',
            chunkKey: 'bicol',
            parentPath: 'Luzon > Region V',
            center: [13.8000, 124.2500],
            zoom: 10,
            bounds: [
              [13.50, 124.00],
              [14.15, 124.55],
            ],
          },
          {
            id: 'masbate',
            name: 'Masbate Province',
            shortName: 'Masbate',
            type: 'province',
            chunkKey: 'bicol',
            parentPath: 'Luzon > Region V',
            center: [12.2500, 123.5000],
            zoom: 9,
            bounds: [
              [11.70, 123.05],
              [12.85, 124.15],
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'visayas',
    name: 'Visayas Island Group',
    shortName: 'Visayas',
    type: 'island_group',
    chunkKey: 'panay_guimaras',
    center: [10.8, 123.5],
    zoom: 7,
    children: [
      {
        id: 'panay_guimaras',
        name: 'Region VI (Western Visayas)',
        shortName: 'Western Visayas',
        type: 'region',
        chunkKey: 'panay',
        parentPath: 'Visayas',
        center: [10.8500, 122.7500],
        zoom: 8,
        bounds: [
          [9.40, 121.25],
          [12.15, 123.60],
        ],
        children: [
          {
            id: 'panay',
            name: 'Panay Island (Full)',
            shortName: 'Panay',
            type: 'province',
            chunkKey: 'panay',
            parentPath: 'Visayas > Region VI',
            center: [11.0000, 122.5000],
            zoom: 8,
            bounds: [
              [10.35, 121.75],
              [12.15, 123.45],
            ],
          },
          {
            id: 'iloilo',
            name: 'Iloilo Province',
            shortName: 'Iloilo',
            type: 'province',
            chunkKey: 'iloilo',
            parentPath: 'Visayas > Region VI',
            center: [11.0528, 122.6925],
            zoom: 9,
            bounds: [
              [10.4668, 122.0122],
              [11.6388, 123.3727],
            ],
          },
          {
            id: 'capiz',
            name: 'Capiz Province',
            shortName: 'Capiz',
            type: 'province',
            chunkKey: 'capiz',
            parentPath: 'Visayas > Region VI',
            center: [11.3755, 122.6487],
            zoom: 10,
            bounds: [
              [11.1335, 122.1999],
              [11.6175, 123.0976],
            ],
          },
          {
            id: 'aklan',
            name: 'Aklan Province',
            shortName: 'Aklan',
            type: 'province',
            chunkKey: 'aklan',
            parentPath: 'Visayas > Region VI',
            center: [11.6555, 122.2102],
            zoom: 10,
            bounds: [
              [11.3129, 121.8436],
              [11.9982, 122.5768],
            ],
          },
          {
            id: 'antique',
            name: 'Antique Province',
            shortName: 'Antique',
            type: 'province',
            chunkKey: 'antique',
            parentPath: 'Visayas > Region VI',
            center: [11.3066, 121.8032],
            zoom: 9,
            bounds: [
              [10.4064, 121.2827],
              [12.2069, 122.3237],
            ],
          },
          {
            id: 'guimaras',
            name: 'Guimaras Province',
            shortName: 'Guimaras',
            type: 'province',
            chunkKey: 'panay_guimaras',
            parentPath: 'Visayas > Region VI',
            center: [10.5925, 122.5900],
            zoom: 10,
            bounds: [
              [10.4400, 122.4700],
              [10.7450, 122.7100],
            ],
          },
          {
            id: 'r6_negros',
            name: 'Negros Occidental',
            shortName: 'Negros Occ',
            type: 'province',
            chunkKey: 'panay_guimaras',
            parentPath: 'Visayas > Region VI',
            center: [10.6765, 122.9509],
            zoom: 9,
            bounds: [
              [9.4000, 122.4000],
              [11.0000, 123.6000],
            ],
          },
        ],
      },
      {
        id: 'central_visayas',
        name: 'Region VII (Central Visayas)',
        shortName: 'Central Visayas',
        type: 'region',
        chunkKey: 'central_visayas',
        parentPath: 'Visayas',
        center: [10.1000, 123.9000],
        zoom: 9,
        bounds: [
          [9.00, 122.55],
          [11.65, 124.75],
        ],
        children: [
          {
            id: 'cebu',
            name: 'Cebu Province & City',
            shortName: 'Cebu',
            type: 'province',
            chunkKey: 'central_visayas',
            parentPath: 'Visayas > Region VII',
            center: [10.3157, 123.8854],
            zoom: 9,
            bounds: [
              [9.4000, 123.2500],
              [11.3500, 124.1500],
            ],
          },
          {
            id: 'bohol',
            name: 'Bohol Province',
            shortName: 'Bohol',
            type: 'province',
            chunkKey: 'central_visayas',
            parentPath: 'Visayas > Region VII',
            center: [9.8500, 124.1435],
            zoom: 10,
            bounds: [
              [9.5000, 123.7000],
              [10.2000, 124.6000],
            ],
          },
          {
            id: 'negros_oriental',
            name: 'Negros Oriental',
            shortName: 'Negros Or',
            type: 'province',
            chunkKey: 'central_visayas',
            parentPath: 'Visayas > Region VII',
            center: [9.6000, 123.0000],
            zoom: 9,
            bounds: [
              [9.0000, 122.7500],
              [10.5000, 123.4000],
            ],
          },
          {
            id: 'siquijor',
            name: 'Siquijor Province',
            shortName: 'Siquijor',
            type: 'province',
            chunkKey: 'central_visayas',
            parentPath: 'Visayas > Region VII',
            center: [9.2000, 123.5500],
            zoom: 11,
            bounds: [
              [9.1000, 123.4000],
              [9.3000, 123.7000],
            ],
          },
        ],
      },
      {
        id: 'eastern_visayas',
        name: 'Region VIII (Eastern Visayas)',
        shortName: 'Eastern Visayas',
        type: 'region',
        chunkKey: 'eastern_visayas',
        parentPath: 'Visayas',
        center: [11.2443, 125.0039],
        zoom: 8,
        bounds: [
          [9.85, 123.95],
          [12.80, 126.05],
        ],
        children: [
          {
            id: 'leyte',
            name: 'Leyte (Tacloban)',
            shortName: 'Leyte',
            type: 'province',
            chunkKey: 'eastern_visayas',
            parentPath: 'Visayas > Region VIII',
            center: [11.2444, 125.0039],
            zoom: 9,
            bounds: [
              [10.3500, 124.2500],
              [11.6000, 125.2000],
            ],
          },
          {
            id: 'samar',
            name: 'Samar (Western Samar)',
            shortName: 'Samar',
            type: 'province',
            chunkKey: 'eastern_visayas',
            parentPath: 'Visayas > Region VIII',
            center: [11.8000, 124.9000],
            zoom: 9,
            bounds: [
              [11.2000, 124.4000],
              [12.3000, 125.3500],
            ],
          },
          {
            id: 'eastern_samar',
            name: 'Eastern Samar',
            shortName: 'E. Samar',
            type: 'province',
            chunkKey: 'eastern_visayas',
            parentPath: 'Visayas > Region VIII',
            center: [11.6000, 125.4500],
            zoom: 9,
            bounds: [
              [10.9500, 125.2000],
              [12.2500, 125.7500],
            ],
          },
          {
            id: 'northern_samar',
            name: 'Northern Samar',
            shortName: 'N. Samar',
            type: 'province',
            chunkKey: 'eastern_visayas',
            parentPath: 'Visayas > Region VIII',
            center: [12.4500, 124.6500],
            zoom: 9,
            bounds: [
              [12.2000, 124.1500],
              [12.7500, 125.2000],
            ],
          },
          {
            id: 'southern_leyte',
            name: 'Southern Leyte',
            shortName: 'S. Leyte',
            type: 'province',
            chunkKey: 'eastern_visayas',
            parentPath: 'Visayas > Region VIII',
            center: [10.3000, 125.0000],
            zoom: 10,
            bounds: [
              [9.8500, 124.7500],
              [10.6000, 125.3000],
            ],
          },
          {
            id: 'biliran',
            name: 'Biliran Province',
            shortName: 'Biliran',
            type: 'province',
            chunkKey: 'eastern_visayas',
            parentPath: 'Visayas > Region VIII',
            center: [11.6000, 124.5000],
            zoom: 11,
            bounds: [
              [11.4500, 124.3500],
              [11.7500, 124.6500],
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'mindanao',
    name: 'Mindanao Island Group',
    shortName: 'Mindanao',
    type: 'island_group',
    chunkKey: 'mindanao_south',
    center: [7.8, 125.0],
    zoom: 7,
    children: [
      {
        id: 'zamboanga_peninsula',
        name: 'Region IX (Zamboanga Peninsula)',
        shortName: 'Zamboanga',
        type: 'region',
        chunkKey: 'zamboanga_peninsula',
        parentPath: 'Mindanao',
        center: [7.8385, 122.7560],
        zoom: 8,
        bounds: [
          [6.80, 121.85],
          [8.90, 123.75],
        ],
        children: [
          {
            id: 'zamboanga_del_sur',
            name: 'Zamboanga del Sur (Zamboanga City)',
            shortName: 'Zambo Sur',
            type: 'province',
            chunkKey: 'zamboanga_peninsula',
            parentPath: 'Mindanao > Region IX',
            center: [7.3500, 122.8000],
            zoom: 9,
            bounds: [
              [6.85, 121.90],
              [8.10, 123.65],
            ],
          },
          {
            id: 'zamboanga_del_norte',
            name: 'Zamboanga del Norte (Dipolog)',
            shortName: 'Zambo Norte',
            type: 'province',
            chunkKey: 'zamboanga_peninsula',
            parentPath: 'Mindanao > Region IX',
            center: [8.3500, 123.1500],
            zoom: 9,
            bounds: [
              [7.65, 121.95],
              [8.85, 123.60],
            ],
          },
          {
            id: 'zamboanga_sibugay',
            name: 'Zamboanga Sibugay',
            shortName: 'Sibugay',
            type: 'province',
            chunkKey: 'zamboanga_peninsula',
            parentPath: 'Mindanao > Region IX',
            center: [7.7500, 122.7000],
            zoom: 9,
            bounds: [
              [7.40, 122.30],
              [8.05, 123.15],
            ],
          },
        ],
      },
      {
        id: 'northern_mindanao_caraga',
        name: 'Region X (Northern Mindanao)',
        shortName: 'Northern Mindanao',
        type: 'region',
        chunkKey: 'northern_mindanao_caraga',
        parentPath: 'Mindanao',
        center: [8.4542, 124.6319],
        zoom: 8,
        bounds: [
          [7.50, 123.50],
          [9.35, 125.40],
        ],
        children: [
          {
            id: 'misamis_oriental',
            name: 'Misamis Oriental (CDO)',
            shortName: 'Mis. Oriental',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region X',
            center: [8.6500, 124.7500],
            zoom: 9,
            bounds: [
              [8.25, 124.25],
              [9.10, 125.35],
            ],
          },
          {
            id: 'bukidnon',
            name: 'Bukidnon Province',
            shortName: 'Bukidnon',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region X',
            center: [8.0500, 125.0500],
            zoom: 9,
            bounds: [
              [7.45, 124.50],
              [8.65, 125.45],
            ],
          },
          {
            id: 'lanao_del_norte',
            name: 'Lanao del Norte (Iligan)',
            shortName: 'Lanao Norte',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region X',
            center: [8.0500, 124.0000],
            zoom: 9,
            bounds: [
              [7.75, 123.60],
              [8.40, 124.45],
            ],
          },
          {
            id: 'misamis_occidental',
            name: 'Misamis Occidental',
            shortName: 'Mis. Occidental',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region X',
            center: [8.4000, 123.7000],
            zoom: 10,
            bounds: [
              [8.00, 123.45],
              [8.75, 123.90],
            ],
          },
          {
            id: 'camiguin',
            name: 'Camiguin Island',
            shortName: 'Camiguin',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region X',
            center: [9.1700, 124.7200],
            zoom: 11,
            bounds: [
              [9.05, 124.60],
              [9.30, 124.85],
            ],
          },
        ],
      },
      {
        id: 'mindanao_south',
        name: 'Region XI (Davao Region)',
        shortName: 'Davao Region',
        type: 'region',
        chunkKey: 'mindanao_south',
        parentPath: 'Mindanao',
        center: [7.1907, 125.4504],
        zoom: 8,
        bounds: [
          [5.30, 125.10],
          [8.05, 126.65],
        ],
        children: [
          {
            id: 'davao',
            name: 'Davao City & del Sur',
            shortName: 'Davao',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XI',
            center: [7.1907, 125.4504],
            zoom: 9,
            bounds: [
              [6.50, 125.15],
              [7.55, 125.75],
            ],
          },
          {
            id: 'davao_del_norte',
            name: 'Davao del Norte (Tagum)',
            shortName: 'Davao Norte',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XI',
            center: [7.5500, 125.7500],
            zoom: 9,
            bounds: [
              [7.15, 125.50],
              [7.95, 126.10],
            ],
          },
          {
            id: 'davao_de_oro',
            name: 'Davao de Oro (Compostela)',
            shortName: 'Davao de Oro',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XI',
            center: [7.5500, 126.0500],
            zoom: 9,
            bounds: [
              [7.10, 125.75],
              [7.95, 126.35],
            ],
          },
          {
            id: 'davao_oriental',
            name: 'Davao Oriental (Mati)',
            shortName: 'Davao Oriental',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XI',
            center: [7.2500, 126.4000],
            zoom: 9,
            bounds: [
              [6.40, 125.95],
              [8.00, 126.65],
            ],
          },
          {
            id: 'davao_occidental',
            name: 'Davao Occidental',
            shortName: 'Davao Occ',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XI',
            center: [6.2500, 125.6500],
            zoom: 9,
            bounds: [
              [5.35, 125.35],
              [6.60, 125.80],
            ],
          },
        ],
      },
      {
        id: 'r12',
        name: 'Region XII (SOCCSKSARGEN)',
        shortName: 'SOCCSKSARGEN',
        type: 'region',
        chunkKey: 'mindanao_south',
        parentPath: 'Mindanao',
        center: [6.5064, 124.8480],
        zoom: 8,
        bounds: [
          [5.50, 124.00],
          [7.65, 125.60],
        ],
        children: [
          {
            id: 'south_cotabato',
            name: 'South Cotabato (GenSan)',
            shortName: 'South Cotabato',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XII',
            center: [6.2500, 124.9500],
            zoom: 9,
            bounds: [
              [5.95, 124.60],
              [6.60, 125.35],
            ],
          },
          {
            id: 'cotabato',
            name: 'Cotabato (North Cotabato)',
            shortName: 'Cotabato',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XII',
            center: [7.1500, 124.9500],
            zoom: 9,
            bounds: [
              [6.70, 124.45],
              [7.65, 125.45],
            ],
          },
          {
            id: 'sarangani',
            name: 'Sarangani Province',
            shortName: 'Sarangani',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XII',
            center: [5.9500, 125.2500],
            zoom: 9,
            bounds: [
              [5.50, 124.35],
              [6.35, 125.60],
            ],
          },
          {
            id: 'sultan_kudarat',
            name: 'Sultan Kudarat',
            shortName: 'Sultan Kudarat',
            type: 'province',
            chunkKey: 'mindanao_south',
            parentPath: 'Mindanao > Region XII',
            center: [6.6500, 124.4500],
            zoom: 9,
            bounds: [
              [6.25, 124.00],
              [7.05, 124.85],
            ],
          },
        ],
      },
      {
        id: 'r13',
        name: 'Region XIII (Caraga)',
        shortName: 'Caraga',
        type: 'region',
        chunkKey: 'northern_mindanao_caraga',
        parentPath: 'Mindanao',
        center: [8.9511, 125.5288],
        zoom: 8,
        bounds: [
          [7.85, 125.20],
          [10.25, 126.55],
        ],
        children: [
          {
            id: 'agusan_del_norte',
            name: 'Agusan del Norte (Butuan)',
            shortName: 'Agusan Norte',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region XIII',
            center: [8.9511, 125.5288],
            zoom: 10,
            bounds: [
              [8.65, 125.25],
              [9.40, 125.80],
            ],
          },
          {
            id: 'agusan_del_sur',
            name: 'Agusan del Sur',
            shortName: 'Agusan Sur',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region XIII',
            center: [8.5000, 125.8000],
            zoom: 9,
            bounds: [
              [7.85, 125.35],
              [8.95, 126.25],
            ],
          },
          {
            id: 'surigao_del_norte',
            name: 'Surigao del Norte (Siargao)',
            shortName: 'Surigao Norte',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region XIII',
            center: [9.7500, 125.7000],
            zoom: 10,
            bounds: [
              [9.35, 125.40],
              [10.15, 126.15],
            ],
          },
          {
            id: 'surigao_del_sur',
            name: 'Surigao del Sur',
            shortName: 'Surigao Sur',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region XIII',
            center: [8.8500, 126.1500],
            zoom: 9,
            bounds: [
              [7.95, 125.85],
              [9.45, 126.55],
            ],
          },
          {
            id: 'dinagat_islands',
            name: 'Dinagat Islands',
            shortName: 'Dinagat',
            type: 'province',
            chunkKey: 'northern_mindanao_caraga',
            parentPath: 'Mindanao > Region XIII',
            center: [10.1000, 125.6000],
            zoom: 10,
            bounds: [
              [9.85, 125.45],
              [10.45, 125.75],
            ],
          },
        ],
      },
      {
        id: 'barmm',
        name: 'BARMM (Bangsamoro)',
        shortName: 'BARMM',
        type: 'region',
        chunkKey: 'barmm',
        parentPath: 'Mindanao',
        center: [7.2047, 124.2384],
        zoom: 8,
        bounds: [
          [4.50, 118.00],
          [8.25, 125.10],
        ],
        children: [
          {
            id: 'maguindanao',
            name: 'Maguindanao (Norte & Sur)',
            shortName: 'Maguindanao',
            type: 'province',
            chunkKey: 'barmm',
            parentPath: 'Mindanao > BARMM',
            center: [7.1000, 124.3000],
            zoom: 9,
            bounds: [
              [6.55, 123.85],
              [7.45, 124.85],
            ],
          },
          {
            id: 'lanao_del_sur',
            name: 'Lanao del Sur (Marawi)',
            shortName: 'Lanao Sur',
            type: 'province',
            chunkKey: 'barmm',
            parentPath: 'Mindanao > BARMM',
            center: [7.9000, 124.3000],
            zoom: 9,
            bounds: [
              [7.35, 123.95],
              [8.15, 124.75],
            ],
          },
          {
            id: 'basilan',
            name: 'Basilan Province',
            shortName: 'Basilan',
            type: 'province',
            chunkKey: 'barmm',
            parentPath: 'Mindanao > BARMM',
            center: [6.6000, 122.0500],
            zoom: 10,
            bounds: [
              [6.25, 121.75],
              [6.85, 122.35],
            ],
          },
          {
            id: 'sulu',
            name: 'Sulu Archipelago (Jolo)',
            shortName: 'Sulu',
            type: 'province',
            chunkKey: 'barmm',
            parentPath: 'Mindanao > BARMM',
            center: [5.9500, 121.0500],
            zoom: 9,
            bounds: [
              [5.45, 120.40],
              [6.35, 121.65],
            ],
          },
          {
            id: 'tawi_tawi',
            name: 'Tawi-Tawi Province',
            shortName: 'Tawi-Tawi',
            type: 'province',
            chunkKey: 'barmm',
            parentPath: 'Mindanao > BARMM',
            center: [5.1500, 119.9500],
            zoom: 9,
            bounds: [
              [4.50, 118.00],
              [5.75, 120.75],
            ],
          },
        ],
      },
    ],
  },
];

// Flat lookup map for quick O(1) resolution by ID
const FLAT_TREE_MAP: Map<string, RegionTreeNode> = new Map();

function buildFlatMap(nodes: RegionTreeNode[]) {
  nodes.forEach((node) => {
    FLAT_TREE_MAP.set(node.id.toLowerCase(), node);
    if (node.children) {
      buildFlatMap(node.children);
    }
  });
}
buildFlatMap(PHILIPPINES_REGION_TREE);

/**
 * Resolves any region or province node by key
 */
export function findRegionTreeNode(id: string | null | undefined): RegionTreeNode | null {
  if (!id) return null;
  const key = id.toLowerCase().trim();
  return FLAT_TREE_MAP.get(key) || null;
}

/**
 * Returns full path breadcrumb string for trigger button display
 * e.g., "Western Visayas > Iloilo Province"
 */
export function getRegionNodePath(id: string | null | undefined): string {
  const node = findRegionTreeNode(id);
  if (!node) return 'Panay Island (Default)';
  if (node.type === 'nationwide') return node.name;
  if (node.parentPath) {
    return `${node.parentPath} > ${node.name}`;
  }
  return node.name;
}

/**
 * Resolves bounds for a given region/province key
 */
export function getRegionNodeBounds(id: string | null | undefined): [[number, number], [number, number]] | null {
  const node = findRegionTreeNode(id);
  if (node && node.bounds) {
    return node.bounds;
  }
  return null;
}
